---
title: "Expert advice from experts"
author:
- familyname: Curie
  othernames: Marie
  address: University of Paris
  qualifications: Nobel Prize, PhD
- familyname: Curie
  othernames: Pierre
  address: University of Paris
  qualifications: Nobel Prize, PhD
email: mcurie.notreal@gmail.com
phone: (03) 9905 2478
department: Department of\newline Econometrics &\newline Business Statistics
organization: Acme Corporation
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  monash::report:
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache=TRUE, messages=FALSE, warning=FALSE)
library(ggplot2)
library(dplyr)
covid <- read.csv("worldwidecases.csv")
```


# Introduction

```{r}
Covid19<- read.csv("worldwidecases.csv")
```

```{r}
Covid19
```

```{r}
library(tidyverse)

covidrate_vis <- Covid19 %>%
mutate(date= as.Date(dateRep, format = "%d/%m/%y"),
cases_rates = ((1000*cases/popData2018) + 0.01),
dead_rates = ((1000*deaths/popData2018) +0.01)) %>%
dplyr::filter(date != "2020-12-31") %>%
#group_by(countriesAndTerritories, date) %>%
#summarize_at(vars(cases, deaths), cumsum) %>%
dplyr::filter(countriesAndTerritories %in%
c("Italy",
"Germany",
"Greece",
"Switzerland",
"Sweden",
"France")) %>%
ggplot(aes(x = date, y = cases_rates) ) +
geom_line(color = "#1F9E8E") +
facet_wrap(~countriesAndTerritories) +
theme_bw() +
ggtitle("Covid cases (rates)")
covidrate_vis
```


Hello， this is the exercise by Tarsha and Albert.

